[package]
name = "actionkv"
version = "0.1.0"
edition = "2021"
authors = ["TS McNamara, <author@rustinaction.com"]

[dependencies]
byteorder = "1.2"
crc = "1.7"

[lib]
name = "libactionkv"
path = "src/lib.rs"

[[bin]]
name = "akv_mem"
path = "src/akv_mem.rs"