[package]
name = "serde-eg"
version = "0.1.0"
edition = "2021"
authors = ["TS McNamara <author@rustinaction.com>"]

[dependencies]
bincode = "1"
serde = "1"
serde_cbor = "0.8"
serde_derive = "1"
serde_json = "1"